services:
    samba:
        image: dockurr/samba
        container_name: samba
        restart: unless-stopped
        environment:
            NAME: "Meow"
            USER: "void"
            PASS: "${SAMBA_PASSWORD}"
        ports:
            - ${TAILSCALE_IP}:445:445
        networks:
            - proxy
        volumes:
            # home storage share for this box's admin user (admin_user in ansible)
            - /home/rasto:/storage/meow
            - /mnt/data:/storage/data
            - /mnt/data/torrents/media:/storage/media
            - ${DOCKER_DATA:-/home/meow/docker-data}/paperless/consume:/storage/paperless-inbox
            - ${DOCKER_DATA:-/home/meow/docker-data}/paperless/export:/storage/paperless-export
            - ${DOCKER_DATA:-/home/meow/docker-data}/running/data:/storage/running

networks:
    proxy:
        external: true
