services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    labels:
      caddy: dockhand.${DOMAIN_NAME:-mnau.org}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DATA:-/home/meow/docker-data}/dockhand/data:/app/data
      - /mnt/data/backup:/mnt/data/backup
    environment:
      - FEAT_BACKUPS_ENABLED=true

networks:
  proxy:
    external: true
