services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.mnau.org"
      SIGNUPS_ENABLED: "false"
    labels:
      caddy: vaultwarden.${DOMAIN_NAME:-mnau.org}
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      - ${DOCKER_DATA:-/home/meow/docker-data}/vaultwarden/data:/data/
    networks:
      - proxy

networks:
    proxy:
        external: true
