services:
  moe-counter:
    image: ghcr.io/journey-ad/moe-counter:latest
    container_name: moe-counter
    restart: unless-stopped
    environment:
      APP_PORT: 3000
      APP_SITE: https://counter.mnau.org
      DB_TYPE: sqlite
      DB_INTERVAL: 60
      LOG_LEVEL: info
    volumes:
      - ${DOCKER_DATA:-/home/meow/docker-data}/moe-counter/data:/app/data
    networks:
        - public

networks:
    public:
        external: true
