---
# Bookmarks: https://gethomepage.dev/configs/bookmarks

- Dev:
      - Forgejo:
            - abbr: FG
              href: https://forgejo.mnau.org/
      - GitHub:
            - abbr: GH
              href: https://github.com/

- Cloud:
      - Oracle Cloud:
            - abbr: OC
              href: https://cloud.oracle.com/
      - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
      - Tailscale:
            - abbr: TS
              href: https://login.tailscale.com/admin/machines
