---
# Info widgets: https://gethomepage.dev/configs/info-widgets/

- resources:
      cpu: true
      memory: true
      disk: /

- search:
      provider: searxng
      url: https://search.mnau.org/
      target: _blank
