---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
      cpu: true
      memory: true
      disk: /
# - docker:
#       server: my-docker
#       label: Containers
#       running: true
# - datetime:
#       text_size: sm
#       format:
#           timeStyle: short
#           dateStyle: short
# - search:
#     provider: duckduckgo
#     target: _blank
