baseURL = "https://blog.mnau.org/"
locale = "en-US"
title = "Mnau :3"
theme = "PaperMod"

enableRobotsTXT = true
mainSections = ["posts"]

[params]
description = "Blog about things I like"
defaultTheme = "auto"
ShowReadingTime = true
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

# [[menu.main]]
# name = "Archive"
# url = "/archives/"
# weight = 10

# [[menu.main]]
# name = "Tags"
# url = "/tags/"
# weight = 20

[params.homeInfoParams]
Title = "Heyyyy welcome to my blog"
Content = "Personal blog about self-hosting, books and whatever else I feel like writing about."

[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 30
