services:
    caddy:
        image: meowtainers-caddy
        build:
            context: .
            dockerfile: Dockerfile
        container_name: caddy
        command: caddy docker-proxy --caddyfile-path /etc/caddy/Caddyfile
        ports:
          # tailscale
          - "${TAILSCALE_IP}:80:80"
          - "${TAILSCALE_IP}:443:443"
          - "${TAILSCALE_IP}:443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ${DOCKER_DATA:-/home/meow/docker-data}/caddy/data:/data
            - ${DOCKER_DATA:-/home/meow/docker-data}/caddy/config:/config
            - ${DOCKER_DATA:-/home/meow/docker-data}/caddy/logs:/var/log/caddy
        environment:
            - CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}
            - DOMAIN=${DOMAIN_NAME}
            - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
        networks:
            - proxy
        restart: unless-stopped
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
            - "dockhand.update=false"

networks:
    proxy:
        external: true
