services:
    freshrss:
        image: freshrss/freshrss:latest
        container_name: freshrss
        restart: unless-stopped
        labels:
            caddy: freshrss.${DOMAIN_NAME:-mnau.org}
            caddy.reverse_proxy: "{{upstreams 80}}"
        environment:
            - TZ=Europe/Prague
            - CRON_MIN=1,31
        networks:
            - proxy
        volumes:
            - ${DOCKER_DATA:-/home/meow/docker-data}/freshrss/data:/var/www/FreshRSS/data
            - ${DOCKER_DATA:-/home/meow/docker-data}/freshrss/extensions:/var/www/FreshRSS/extensions

networks:
    proxy:
        external: true
